### ISSUE TITLE
need to extract country estimates from reef area shapefiles

### ISSUE THREAD

**Issue by jpwrobinson** [baumlab/open-science-project#6]
Jill - thought this was well suited to your skillset - are you able to get us country level reef area estimates from the UNEP shapefiles?

**Comment by jpwrobinson** [comment]
I can't push up the shapefile because I'm in shitty internet land. Here's the citation and link:

UNEP-WCMC, WorldFish Centre, WRI, TNC (2010). Global distribution of warm-water coral reefs, compiled from multiple sources including the Millennium Coral Reef Mapping Project. Version 1.3. Includes contributions from IMaRS-USF and IRD (2005), IMaRS-USF (2005) and Spalding et al. (2001). Cambridge (UK): UNEP World Conservation Monitoring Centre. 

URL: http://data.unep-wcmc.org/datasets/1


You do need to request the file, but it arrives through email 5 mins later.

**Comment by jdunic** [comment]
Great thanks for throwing this my way! I've got the data and will work on this!

**Comment by jdunic** [comment]
Country level reef area estimates now extracted and found in data/reef_area_by_country.csv. 

I also tried the git lfs to allow pointers to big files like the shapefile. Not quite sure what the benefit is though since the big files won't change.

**Comment by jpwrobinson** [comment]
Great, nice work.

Just re: LFS stuff - the reason for using LFS was to avoid exceeding the Github repo size limit (2gb). I just had problems uploading big files. Good to track .shp as LFS though, ta.
